name: Front-end

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ğŸ””
        uses: actions/checkout@v2

      - name: Setup Node ğŸ”§ğŸ”©
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Restore dependencies ğŸ’‰
        run: yarn install
        working-directory: Client/MenuMasters/src

      - name: Build project ğŸ‘·â€â™‚ï¸ğŸ§±
        run: yarn build
        working-directory: Client/MenuMasters/src

      - name: Upload production-ready build files ğŸ”¼ğŸš€
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: Client/MenuMasters/src
